#!/usr/bin/bash

PUPPET_CODE=$1

echo "==================================="
echo "puppet parser validate $PUPPET_CODE"
cat $PUPPET_CODE | ssh puppet.asdflkjh.com puppet parser validate
echo "==================================="

# puppet-lint <path-to-module>
# echo "puppet-lint $PUPPET_CODE"
# cat $PUPPET_CODE | ssh puppet.asdflkjh.com puppet-lint
# echo "==================================="
